# Here we define the names of the numeric replies.
# The names of the numeric replies are taken
# from the RFC 1459.


class Reply(object):
    # Error replies
    ERR_NO_SUCH_NICK = "401"
    ERR_NO_SUCH_SERVER = "402"
    ERR_NO_SUCH_CHANNEL = "403"
    ERR_CANNOT_SEND_TO_CHAN = "404"
    ERR_TOO_MANY_CHANNELS = "405"
    ERR_WAS_NO_SUCH_NICK = "406"  # Returned by WHOWAS
    ERR_TOO_MANY_TARGETS = "407"
    ERR_NO_ORIGIN = "409"
    ERR_NO_RECIPIENT = "411"
    ERR_NO_TEXT_TO_SEND = "412"
    ERR_NO_TOP_LEVEL = "413"
    ERR_WILDCARD_IN_TOP_LEVEL = "414"

    ERR_UNKNOWN_COMMAND = "421"
    ERR_NO_MOTD = "422"
    ERR_NO_ADMIN_INFO = "423"
    ERR_FILE_ERROR = "424"

    ERR_NO_NICKNAME_GIVEN = "431"
    ERR_INVALID_NICKNAME = "432"
    ERR_NICKNAME_IN_USE = "433"
    ERR_NICK_COLLISION = "436"

    ERR_USER_NOT_IN_CHANNEL = "441"
    ERR_NOT_ON_CHANNEL = "442"
    ERR_USER_ALREADY_ON_CHANNEL = "443"
    ERR_NO_LOGIN = "444"
    ERR_SUMMON_DISABLED = "445"
    ERR_USERS_DISABLED = "446"

    ERR_NOT_REGISTERED = "451"

    ERR_NEED_MORE_PARAMS = "461"
    ERR_ALREADY_REGISTERED = "462"
    ERR_NO_PERM_FOR_HOST = "463"
    ERR_INCORRECT_PASSWORD = "464"
    ERR_YOU_ARE_BANNED = "465"
    ERR_KEY_ALREADY_SET = "467"

    ERR_CHANNEL_IS_FULL = "471"
    ERR_CHANNEL_MODE_UNKNOWN_FLAG = "472"
    ERR_INVITEONLY_CHAN = "473"
    ERR_BANNED_FROM_CHAN = "474"
    ERR_BAD_CHANNEL_KEY = "475"

    ERR_NO_PRIVILEGES = "481"
    ERR_CHAN_OP_PRIVILEGE_NEEDED = "482"
    ERR_CANT_KILL_SERVER = "483"

    ERR_NO_OPER_HOST = "491"

    ERR_USER_MODE_UNKNOWN_FLAG = "501"
    ERR_USERS_DONT_MATCH = "502"

    # Command responses
    RPL_NONE = "300"
    RPL_USERHOST = "302"
    RPL_IS_ON = "303"     # Used by message ISON
    RPL_USER_AWAY = "301"      # Refers to other users being away
    RPL_YOU_ARE_BACK = "305"
    RPL_YOU_ARE_AWAY = "306"

    RPL_WHOIS_USER = "311"
    RPL_WHOIS_SERVER = "312"
    RPL_WHOIS_OPERATOR = "313"
    RPL_WHOIS_IDLE = "317"
    RPL_END_OF_WHOIS = "318"
    RPL_WHOIS_CHANNELS = "319"

    RPL_WHOWAS_USER = "314"
    RPL_END_OF_WHOWAS = "369"

    RPL_LIST_START = "321"
    RPL_LIST = "322"
    RPL_LIST_END = "323"
    RPL_CHANNEL_MODE_IS = "324"

    RPL_NO_TOPIC = "331"
    RPL_TOPIC = "332"

    RPL_INVITING = "341"
    RPL_SUMMONING = "342"

    RPL_VERSION = "351"

    RPL_WHO_REPLY = "352"
    RPL_END_OF_WHO = "315"

    RPL_NAME_REPLY = "353"
    RPL_END_OF_NAMES = "366"

    RPL_LINKS = "364"
    RPL_END_OF_LINKS = "365"

    RPL_BANLIST = "367"
    RPL_END_OF_BANLIST = "368"

    RPL_INFO = "371"
    RPL_END_OF_INFO = "374"

    RPL_MOTD_START = "375"
    RPL_MOTD = "372"
    RPL_END_OF_MOTD = "376"

    RPL_YOU_ARE_OP = "381"
    RPL_REHASHING = "382"

    RPL_TIME = "391"

    RPL_USERS_START = "392"
    RPL_USERS = "393"
    RPL_END_OF_USERS = "394"
    RPL_NO_USERS = "395"

    RPL_TRACE_LINK = "200"
    RPL_TRACE_CONNECTING = "201"
    RPL_TRACE_HANDSHAKE = "202"
    RPL_TRACE_UNKNOWN = "203"
    RPL_TRACE_OPERATOR = "204"
    RPL_TRACE_USER = "205"
    RPL_TRACE_SERVER = "206"
    RPL_TRACE_NEWTYPE = "208"
    RPL_TRACELOG = "261"

    RPL_STATS_LINK_INFO = "211"
    RPL_STATS_COMMANDS = "212"
    RPL_STATS_CLINE = "213"
    RPL_STATS_NLINE = "214"
    RPL_STATS_ILINE = "215"
    RPL_STATS_KLINE = "216"
    RPL_STATS_YLINE = "218"
    RPL_END_OF_STATS = "219"
    RPL_STATS_LLINE = "241"
    RPL_STATS_UPTIME = "242"
    RPL_STATS_OLINE = "243"
    RPL_STATS_HLINE = "244"

    RPL_USER_MODE_IS = "221"

    RPL_L_USER_CLIENT = "251"
    RPL_L_USER_OP = "252"
    RPL_L_USER_UNKNOWN = "253"
    RPL_L_USER_CHANNELS = "254"
    RPL_L_USER_ME = "255"

    RPL_ADMIN_ME = "256"
    RPL_ADMIN_LOC1 = "257"
    RPL_ADMIN_LOC2 = "258"
    RPL_ADMIN_EMAIL = "259"


_reply_names = {}
for key in Reply.__dict__:
    val = Reply.__dict__[key]

    assert val not in _reply_names
    _reply_names[val] = key

def get_reply_name(num):
    return _reply_names[num]


if __name__ == "__main__":
    print(Reply.ERR_NOOPERHOST)
    print(get_reply_name(Reply.ERR_NOOPERHOST))